### ISSUE TITLE
Not working on safari 

### ISSUE THREAD

**Issue by arochedy** [jacobbuck/react-outer-click#5]
Hi, 

I'm using this awesome library. It's work well for chrome/brave etc.. but not on safari (for mac I didn't tested it on iphone)

Do you know why ? do you have ideas to make it work on safari ?

**Comment by jacobbuck** [comment]
That's interesting, I'm not having any issues with Safari on my end. Would you be able to provide any steps to reproduce the issue?

**Comment by arochedy** [comment]
My bad ! There is no issue on safari. 

The problem was because I wanted to filter event. What I wanted was "If the user click on this part of the page, I don't do the action". My solution only works on chromium navigators. I update my way of doing this and now it's ok
